
package com.zadanie.server.ws.client;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-b02-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "WServiceService", targetNamespace = "http://client.ws.server.zadanie.com/", wsdlLocation = "http://localhost:8080/test")
public class WServiceService
    extends Service
{

    private final static URL WSERVICESERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.zadanie.server.ws.client.WServiceService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.zadanie.server.ws.client.WServiceService.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:8088/mockWService?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8080/test', retrying as a local file");
            logger.warning(e.getMessage());
        }
        WSERVICESERVICE_WSDL_LOCATION = url;
    }

    public WServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WServiceService() {
        super(WSERVICESERVICE_WSDL_LOCATION, new QName("http://client.ws.server.zadanie.com/", "WServiceMockService"));
    }

    /**
     * 
     * @return
     *     returns WService
     */
    @WebEndpoint(name = "WServicePort")
    public WService getWServicePort() {
        return super.getPort(new QName("http://client.ws.server.zadanie.com/", "WServicePort"), WService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WService
     */
    @WebEndpoint(name = "WServicePort")
    public WService getWServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://client.ws.server.zadanie.com/", "WServicePort"), WService.class, features);
    }

}
