
package com.zadanie.server.ws.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-b02-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "WService", targetNamespace = "http://client.ws.server.zadanie.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WService {


    /**
     * 
     * @param count
     * @param ip
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addCount", targetNamespace = "http://client.ws.server.zadanie.com/", className = "com.zadanie.server.ws.client.AddCount")
    @ResponseWrapper(localName = "addCountResponse", targetNamespace = "http://client.ws.server.zadanie.com/", className = "com.zadanie.server.ws.client.AddCountResponse")
    public int addCount(
        @WebParam(name = "count", targetNamespace = "")
        Integer count,
        @WebParam(name = "ip", targetNamespace = "")
        String ip);

}
